apiVersion: v1
kind: ConfigMap
metadata:
  name: closingtag-notification-service-db-configmap
data:
  db-host: "closingtag-notification-service-db-svc"
  db-name: "ct_device_service_db"
  db-port: "5432"

---
apiVersion: v1
kind: Secret
metadata:
  name: closingtag-notification-service-db-secret
data:
  db-user: "cG9zdGdyZXM="  # postgres
  db-pass: "cm9vdA=="  # root

type: Opaque

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: closingtag-notification-service-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: closingtag-notification-service-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: closingtag-notification-service-db-deployment
spec:
  selector:
    matchLabels:
      app: closingtag-notification-service-db
  replicas: 1
  template:
    metadata:
      labels:
        app: closingtag-notification-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "50m"
              memory: "96Mi"
            requests:
              cpu: "40m"
              memory: "64Mi"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: closingtag-notification-service-db-secret
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: closingtag-notification-service-db-secret
                  key: db-pass
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: closingtag-notification-service-db-configmap
                  key: db-name
          volumeMounts:
            - name: db-data
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: closingtag-notification-service-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: closingtag-notification-service-db-svc
spec:
  selector:
    app: closingtag-notification-service-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
